### ISSUE TITLE
How use this script?

### ISSUE THREAD

**Issue by O1iveira** [Piker-Alpha/freqVectorsEdit.sh#1]
Hi!

How i can use this script? What commands should i use?

Thanks

**Comment by Piker-Alpha** [comment]
See README (as promised).

**Comment by O1iveira** [comment]
Nice!

More 1 doubt! Even using -xcpm, is necessary use SSDT generated by script?

**Comment by Piker-Alpha** [comment]
Yes.

**Comment by O1iveira** [comment]
Ok.
So, i use this patch (freqVectorsEdit.sh), and add xcpm_ignore_fv in arguments and use SSDT, but still give me KP in AICPM.

If i use (freqVectorsEdit.sh), and add -xcpm in arguments and use SSDT, i don't get any KP.
But, i have this errors in boot, see the log:
![captura de tela 2014-11-05 as 14 35 12](https://cloud.githubusercontent.com/assets/9559008/4921363/e66b417c-6509-11e4-9e81-3a36d69f88c9.png)

**Comment by Piker-Alpha** [comment]
Don't use -xcpm_ignore_fv when you want to use XCPM. The rest doesn't belong here.

**Comment by Piker-Alpha** [comment]
That is something unrelated to this script and should be discussed as ssdtPRGen.sh issues. Not here.

**Comment by O1iveira** [comment]
Ok!

Done ;)
