### ISSUE TITLE
Vectors doesn't load in xcpm

### ISSUE THREAD

**Issue by MessyMass** [Piker-Alpha/freqVectorsEdit.sh#10]
Hello Piker! 

Thank you for your awesome work, which i have followed for some time :) 

I've been trying to get XCPM working on Sierra (10.12.3) with 5930K and asus rampage V extreme (running macpro 6.1 smbios), and finally I've had a breakthrough. At least i think so. 

#sysctl -n machdep.xcpm.mode outputs: 1 (xcpm is on) 
and i can see my cpu frequencies change through AppleIntelInfo and Intels power Gadget. 

Now, I want to have XCPM loading the vectors I choose through freqVectorsEdit.sh. The script runs fine with -b Mac-F60DEB81FF30ACF6, and i select Mac-E43C1C25D4880AD6.plist (to get C7 state also), so that should be it? Reboot. 

#sysctl -n machdep.xcpm.vectors_loaded_count: 0 (so no frequencyvectors are being used) 

I've also tried extracting the x89platformplugin.kext from /S/L/E/IOPlatformPlugin.kext, renaming the file, changing the version numbers in info.plist to 9.1.1 and removing/renaming the appropriate plist file for my SMBIOS. I then change the permissions back to root:wheel etc, load it, but it doesn't get included in kextstat when i restart... 

I've been busting my brain about this for too long, and i without doubt get bald if i continue. Can you please point me in the right direction - how do I get xcpm to load the frequencyvectors?? 

Thanks! 
Mads

**Comment by MessyMass** [comment]
Naturally after writing you, I got it working through the beta version of ssdtPRGen.sh. Time to test PM on X99 :)

**Comment by Piker-Alpha** [comment]
Ok. Thanks for letting me know. 

-> Closing issue.
