### ISSUE TITLE
How do I know which donor model to choose for the frequency vectors?

### ISSUE THREAD

**Issue by jasperlevi** [Piker-Alpha/freqVectorsEdit.sh#11]
I am using the latest version of your script (v 3.1), and I am having a tough time deciding which frequency vector donor to choose. I am using SMBIOS for MacPro 6,1 for a hackintosh with a Gigabyte X99 UD4 board and an Intel i7 5820K processor. Currently using iMac 15,1 as the donor but no way be sure that it's the right model that I picked...

**Comment by Piker-Alpha** [comment]
Well. There is no model that matches with your processor model but any Mac models with FrequencyVectors in it should work.
