### ISSUE TITLE
IGPU frequency anomaly

### ISSUE THREAD

**Issue by jqqqqqqqqqq** [Piker-Alpha/freqVectorsEdit.sh#13]
I'm i7 4710HQ with HD4600, and before using this script the GT frequency is 0.2G(idle) and 0.5G(active). I tried if this script can modify it and improve the active frequency to 1.2G, which is the frequency under windows and the proper value of the hardware. However, after using this script the idle becomes 0.75G, and when I launch a 3D game(Hearthstone) it drop back to 0.5G and return to 0.75G immediately when I close the game.

**Comment by Piker-Alpha** [comment]
The IGPU settings are untouched by this script. What you see is the result of other frequencies, Which is normal.

-> invalid.
