### ISSUE TITLE
Lose stepcontextdict after running the script. Therefore "Failed to send stepper".

### ISSUE THREAD

**Issue by tengg** [Piker-Alpha/freqVectorsEdit.sh#14]
I noticed the original macpro6,1 plist has the stepcontextdict. But after I running the script and choosing imac17,1. There's only freqency vector and sleep policy in the plist. And after reboot, I saw "Failed to send stepper" in the kernel log.

I'm just confused.. How should I make it work?

**Comment by Piker-Alpha** [comment]
Sorry, but I cannot do anything without a version number and the processor model that you are using.

Yes. The stepcontextdict will be removed by the script, and FrequencyVectors will be injected. As it should.
