### ISSUE TITLE
Execution has no effect

### ISSUE THREAD

**Issue by armenio** [Piker-Alpha/freqVectorsEdit.sh#2]
I have a Haswell Xeon E3 1245 V3 Quad-Core, using macpro6,1 smbios and running freqVectorsEdit.sh first time i dont see Mac-F60DEB81FF30ACF6.plist in list.

Choosing Imac 14,1 the script works without errors but my speed step still no working.

Using imac 14,1 smbios the speed step works fine.

the big question: I need an extra parameter on exec freqVectorsEdit.sh script?

Thank you

**Comment by Piker-Alpha** [comment]
Back in the day, when I wrote this script, people used the new MacPro6,1 SMBIOS data with a Haswell processor, but the plist for it missed the requirerd FrequencyVentors and thus the workaround was to inject it with help of my script.

Later models also have some issues, like using a forced CPUFloor that is higher (1000MHz) than normal. For example. The Broadwell based iMac won't go below 1300MHz without using the data from older Haswell models.

Now back to your question. No. You don't need any arguments when you run my script, but the question is why that you are using a MacPro6,1 SMBIOS for a E3-1245 v3 which in my view is still only a desktop processor model. Not a pro model.
