### ISSUE TITLE
Editting FrequencyVectors in Mac-937CB26E2E02BB01.plist

### ISSUE THREAD

**Issue by nguyenlc1993** [Piker-Alpha/freqVectorsEdit.sh#6]
Hi @Piker-Alpha ,
I'm trying to edit the _FrequencyVectors_ key in X86PlatformPlugin.kext/Contents/Resources/Mac-937CB26E2E02BB01.plist (which corresponds to MacBookAir7,2) to reduce LFM from 1300MHz to 800MHz. But I found 2 subkeys in it, so which key should I edit?

**Note:** I also found 2 subkeys in _Frequencies_ key, 

```
<dict>
    <key>IOPlatformPowerProfile</key>
    <dict>
        ...
        <key>Frequencies</key>
        <dict>
            <key>2700</key>
            <integer>0</integer>
            <key>3200</key>
            <integer>1</integer>
        </dict>
        <key>FrequencyVectors</key>
        <array>
            <data>...</data>
            <data>...</data>
        </array>
```

The values of 2700 and 3200 seem link to the TurboBoost frequency of CPUs used in MacBookAir7,2, namely:

```
Intel Core i5-5250U @ 1.6GHz Turbo 2.7GHz
Intel Core i7-5650U @ 2.2GHz Turbo 3.2GHz
```

And each subkey in FrequencyVectors seems to be used with the corresponding CPU in the list.

I wonder how should I edit the plist to support 3 Broadwell CPUs below:

```
Intel Core i7-5500U @ 2.4GHz Turbo 3.0GHz
Intel Core i5-5200U @ 2.2GHz Turbo 2.7GHz
Intel Core i3-5010U @ 2.1GHz Non-turbo
```

**Comment by Piker-Alpha** [comment]
Ok. The FrequencyVectors of the MacBookAir7,2 are basically the same so you can use Xcode or PlistBuddy. With PlistBuddy you can copy the first entry of the FrequencyVectors with:

```
sudo /usr/libexec/PlistBuddy -c "Copy IOPlatformPowerProfile:FrequencyVectors:0 IOPlatformPowerProfile:FrequencyVectors:2" Mac-937CB26E2E02BB01.plist
```

After which you add 2100 for the Intel i3-5010U to the Frequencies with:

```
sudo /usr/libexec/PlistBuddy -c "Add IOPlatformPowerProfile:Frequencies:2100 integer 2" Mac-937CB26E2E02BB01.plist
```

Then you can change the 0x0d000000 into 0x08000000 with Xcode or whatever value you want to use that is supported by the processors.

**Comment by nguyenlc1993** [comment]
Thank you for your help :D Issue can be closed.

**Comment by Piker-Alpha** [comment]
Great. Glad to hear that this issue is sorted ;)
