### ISSUE TITLE
Can't Add Entry error

### ISSUE THREAD

**Issue by dashbad** [Piker-Alpha/freqVectorsEdit.sh#8]
I'm getting:

Print: Entry, "IOPlatformPowerProfile:FrequencyVectors:0", Does Not Exist
Add: Can't Add Entry, "IOPlatformPowerProfile:FrequencyVectors:0", to Parent

When I select a plist - regardless of plist selected

If I run the script again, I just get:
Add: Can't Add Entry, "IOPlatformPowerProfile:FrequencyVectors:0", to Parent

I'm runnning 10.11.6 on X99 with a i7-5820k

How to debug?

**Comment by dashbad** [comment]
I can see a frequency vectors entry in F60DEB81FF30ACF6.plist after running the script, and this plist now appears as an option in the script output

Does this mean I can ignore this error?

**Comment by Piker-Alpha** [comment]
Yes, because you can – should really – only add the FrequencyVectors data once.
