### ISSUE TITLE
Intel Speed Step Technology falsely reporting

### ISSUE THREAD

**Issue by r2tincan** [Piker-Alpha/freqVectorsEdit.sh#9]
Hi there. Thanks for the tool. Intel Speed Step is reporting enabled for me whether it's disabled in BIOS or not. Newest version. ASUS board.

**Comment by Piker-Alpha** [comment]
Huh? I don't understand this. What you are trying to say. What has this to do with freqVectorsEdit.sh? The script only copies the FrequencyVectors from one plist to another. Where is Intel Speed Step reporting as enabled?

**Comment by Piker-Alpha** [comment]
-> Invalid
